print("hello"[3])
length=len(input("what is your name"))
print(f"You have {length} character ")
# stable=float(40)
stablity=str(40)
stable=float(59.7)
print(type(stable))
# print(float(stable)+float(stablity))
# print(str(stable)+str(stablity))
